version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:10-browsers
  working_directory: ~/styledown


jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  install_dependencies:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - styledown-node10-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Avoid hosts unknown for github
          command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: Npm Install
          command: npm ci
      - save_cache:
          key: styledown-node10-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/styledown/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  # Uncomment after setting up eslint
  # lint:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: .
  #     - run:
  #         name: Lint JavaScript
  #         command: npm run lint:js

  tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests
          command: npm test

workflows:
  version: 2
  default:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - tests:
          requires:
            - install_dependencies
